interface User {
  id: number,
  f_name: string,
  l_name: string,
  e_mail: string,
  password: string,
  active: number,
  avatar: string | null,
  username: string,
  timezone: string,
  balance: number,
  units: number,
  birthday: Date,
  gender: string,
  phone: string,
  address: string | null,
  city: string | null,
  country: string,
  currency: string,
  created: Date,
  kind: string,
  betting_allowed: number,
  op:string | null,
  locale: string,
  monitored: number,
  betlimit: string,
  maxbet: number,
  agent_id: number | null,
  referer: number | null,
  meta: string,
  deposit_bonus: number,
  v: number,
  bet_limit: number,
  live_delay: number,
  severity: number | null,
  redis_token: string,
  deleted: number,
  deleted_at: Date | null,
  kassa_id: number | null,
  gamehub_id: number | null,
  national_id_number: string | null,
  verification_id: string | null,
  migrated: number
}

interface Operator {
  id: number,
  project: string,
  branch: string,
  domain: string,
  parent: string,
  locale: string,
  currency: string,
  binding: number,
  title: string,
  sms: string | null,
  mail: string | null,
  password: string,
  template: string,
  logo: string | null,
  styling: string | null,
  zone: string,
  favicon: string | null,
  time_offset: number,
  country: string,
  country_code: string,
  version: number,
  pos_domain: string | null,
  dash_domain: string,
  agent_domain: string | null,
  header: boolean,
  is_active: boolean,
  V8: boolean,
  client_id: string | null,
  aggregator: string
}

declare enum TR_STATUS {
  INDETERMINATE = 'INDETERMINATE',
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  CANCELED = 'CANCELED',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
  WAITGW = 'WAITGW'
}

interface Transaction {
  id: number,
  user_id: number,
  amount: number,
  status: TR_STATUS,
  op_type: string,
  currency: string,
  updated_at: Date,
  created_at: Date,
  transaction_num: string,
  token: string,
  gateway_token: string,
  gateway_trx_id: string,
  gateway_response: string,
  msisdn: string,
  tries: number,
  meta: string,
  bonus_checked: number,
  upload_id: number
}

export {
  User,
  Operator,
  Transaction
}
