interface User {
  id: number,
  f_name: string,
  l_name: string,
  e_mail: string,
  password: string,
  active: number,
  avatar: string | null,
  username: string,
  timezone: string,
  balance: number,
  units: number,
  birthday: Date,
  gender: string,
  phone: string,
  address: string | null,
  city: string | null,
  country: string,
  currency: string,
  created: Date,
  kind: string,
  betting_allowed: number,
  op:string | null,
  locale: string,
  monitored: number,
  betlimit: string,
  maxbet: number,
  agent_id: number | null,
  referer: number | null,
  meta: string,
  deposit_bonus: number,
  v: number,
  bet_limit: number,
  live_delay: number,
  severity: number | null,
  redis_token: string,
  deleted: number,
  deleted_at: Date | null,
  kassa_id: number | null,
  gamehub_id: number | null,
  national_id_number: string | null,
  verification_id: string | null,
  migrated: number
}

interface Operator {
  id: number,
  project: string,
  branch: string,
  domain: string,
  parent: string,
  locale: string,
  currency: string,
  binding: number,
  title: string,
  sms: string | null,
  mail: string | null,
  password: string,
  template: string,
  logo: string | null,
  styling: string | null,
  zone: string,
  favicon: string | null,
  time_offset: number,
  country: string,
  country_code: string,
  version: number,
  pos_domain: string | null,
  dash_domain: string,
  agent_domain: string | null,
  header: boolean,
  is_active: boolean,
  V8: boolean,
  client_id: string | null,
  aggregator: string
}

declare enum TR_STATUS {
  INDETERMINATE = 'INDETERMINATE',
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  CANCELED = 'CANCELED',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
  WAITGW = 'WAITGW'
}

interface Transaction {
  id: number,
  user_id: number,
  amount: number,
  status: TR_STATUS,
  op_type: string,
  currency: string,
  updated_at: Date,
  created_at: Date,
  transaction_num: string,
  token: string,
  gateway_token: string,
  gateway_trx_id: string,
  gateway_response: string,
  msisdn: string,
  tries: number,
  meta: string,
  bonus_checked: number,
  upload_id: number
}

interface S_bet_prefixed {
  s_bets_id: number,
  s_bets_package_id: string,
  s_bets_date_created: Date | null,
  s_bets_date_calculated: Date | null,
  s_bets_date_paid: Date | null,
  s_bets_shop_id: number,
  s_bets_player_id: number,
  s_bets_employee_id: number,
  s_bets_status: number,
  s_bets_bet_amount: string,
  s_bets_payout_amount: number | null,
  s_bets_paid_amount: number | null,
  s_bets_total_odds: string,
  s_bets_total_rows: number,
  s_bets_total_matches: number,
  s_bets_ztype: number,
  s_bets_hash: string,
  s_bets_is_gb: boolean,
  s_bets_is_paid: boolean,
  s_bets_is_live: boolean,
  s_bets_is_recalc: boolean,
  s_bets_payout_option: number,
  s_bets_paid_shop_id: number,
  s_bets_paid_employee_id: number | null,
  s_bets_bonus: number | null,
  s_bets_bonus_type: number,
  s_bets_currency: string,
  s_bets_promo_type: string | null,
  s_bets_promo_code: string | null,
  s_bets_rate: string | null,
  s_bets_rater_id: string,
  s_bets_note: string,
  s_bets_meta: string,
  s_bets_payout_currency: string,
  s_bets_player_currency: string | null,
  s_bets_archived: boolean
}

interface Log_balance_prefixed {
  log_balance_id: number,
  log_balance_user_id: number,
  log_balance_balance_old_value: string,
  log_balance_balance_new_value: string,
  log_balance_balance_diff: string,
  log_balance_created: Date
  log_balance_units_old_value: string,
  log_balance_units_new_value: string,
  log_balance_units_diff: string,
  log_balance_op: string,
  log_balance_fixed: number,
  log_balance_updated: Date | null,
}

interface Xrate {
  id: number,
  currency: string,
  rate: number,
  updated_at: Date,
  created_at: Date
}

interface Game_casino {
  id: number,
  name: string,
  uuid: string,
  url: string,
  aggregator: string,
  provider: string,
  type: string,
  has_freespins: number,
  technology: string,
  has_demo: number,
  device_support: number,
  image_bg: string,
  image: string,
  priority: number,
  site_section: string,
  marker_type: string | null,
  marker_text: string | null,
  deleted: number,     
  production: number,
  rtp: string,
  frame_size: number
}

export {
  User,
  Operator,
  Transaction,
  S_bet_prefixed,
  Log_balance_prefixed,
  Xrate,
  Game_casino
}
